apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }} 
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }} 
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $) | nindent 8 }}
    spec:
      containers:
        - name: nodejs-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          env:
            - name: GLOBAL_ORG_NAME
              value: {{ .Values.global.env.ORG_NAME | quote }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }} 
      {{- end }} 
